db1:
  image: gouthamve/tns-db
db2:
  image: gouthamve/tns-db
  links:
    - db1
db3:
  image: gouthamve/tns-db
  links:
    - db1
    - db2

app1:
  image: gouthamve/tns-app
  links:
    - db1
    - db2
    - db3
app2:
  image: gouthamve/tns-app
  links:
    - db1
    - db2
    - db3

lb1:
  image: gouthamve/tns-lb
  links:
    - app1
    - app2
  ports:
    - 0.0.0.0:8001:80
lb2:
  image: gouthamve/tns-lb
  links:
    - app1
    - app2
  ports:
    - 0.0.0.0:8002:80
