x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'

version: '3.3'
services:

  db:
    image: grafana/tns-db:9c1ab38
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    logging: *default-logging

  app:
    image: grafana/tns-app:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    logging: *default-logging

  loadgen:
    image: grafana/tns-loadgen:9c1ab38
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    logging: *default-logging

  grafana:
    image: grafana/grafana:7.4.x-exemplars
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
     - "3000:3000"
    logging: *default-logging

  prometheus:
    image: tomwilkie/prometheus:0ea72b6a6
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--enable-feature=exemplar-storage"
      - "--log.level=debug"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    links:
      - app
      - db
      - loadgen
    ports:
      - 0.0.0.0:8003:9090
    logging: *default-logging

  loki:
    image: grafana/loki:2.1.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
        - "3100:3100"
    logging: *default-logging

  tempo:
    image: grafana/tempo:0.5.0
    command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false"]
    ports:
      - "8004:80"
    logging: *default-logging

  tempo-query:
    image: grafana/tempo-query:0.5.0
    environment:
      - BACKEND=tempo
    ports:
      - "8006:16686"
    logging: *default-logging
