version: 2

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - test
    - build
    - lint

defaults: &defaults
  docker:
    - image: golang:1.11.5-stretch
  working_directory: /go/src/github.com/grafana/tns

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: |
            GO111MODULE=on go test ./...

  lint:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Lint
          command: |
            go get -u golang.org/x/lint/golint
            golint ./...

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build Images
          command: |
            make