
db:
  image: grafana/tns-db
  command:
    - '-log.level=debug'
  ports:
    - 0.0.0.0:8000:80
#  environment:
#    JAEGER_AGENT_HOST: jaeger
#    JAEGER_TAGS: cluster=tns,namespace=tns
#    JAEGER_SAMPLE_TYPE: const
#    JAEGER_SAMPLE_PARAM: 1

app:
  image: grafana/tns-app
  command:
    - '-log.level=debug'
    - 'http://db'
  links:
    - db
  ports:
    - 0.0.0.0:8001:80
#  environment:
#    JAEGER_AGENT_HOST: jaeger
#    JAEGER_TAGS: cluster=tns,namespace=tns
#    JAEGER_SAMPLE_TYPE: const
#    JAEGER_SAMPLE_PARAM: 1

loadgen:
  image: grafana/tns-loadgen
  command:
    - '-log.level=debug'
    - 'http://app'
  links:
    - app
  ports:
    - 0.0.0.0:8002:80
#  environment:
#    JAEGER_AGENT_HOST: jaeger
#    JAEGER_TAGS: cluster=tns,namespace=tns
#    JAEGER_SAMPLE_TYPE: const
#    JAEGER_SAMPLE_PARAM: 1
