version: "2"
services:

  db:
    image: grafana/tns-db
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  app:
    image: grafana/tns-app
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  loadgen:
    image: grafana/tns-loadgen
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    environment:
      JAEGER_ENDPOINT: 'http://tempo:14268/api/traces'
      JAEGER_TAGS: cluster=tns,namespace=tns
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1

  grafana:
    image: grafana/grafana:7.4.x-exemplars
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
     - "3000:3000"

  prometheus:
    image: tomwilkie/prometheus:b165c3b91
    user: root
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    links:
      - app
      - db
      - loadgen
    ports:
      - 0.0.0.0:8003:9090

  tempo:
    image: grafana/tempo:0.5.0
    command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false"]
    ports:
      - "8004:80"  # tempo

  tempo-query:
    image: grafana/tempo-query:0.5.0
    environment:
      - BACKEND=tempo
    ports:
      - "8006:16686"  # jaeger-ui
