apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger
  template:
    metadata:
      labels:
        name: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.15
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 16686
        - name: thrift-compact
          containerPort: 6831